basePath: /
definitions:
  main.MessageResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Bu, BeeHub Ders Seçim Botu için API dokümantasyonudur.
  title: BeeHub Ders Seçim Botu API
  version: "1.0"
paths:
  /auth/login:
    get:
      consumes:
      - application/json
      produces:
      - text/html
      responses: {}
      summary: Hello World
      tags:
      - Login
  /hello:
    get:
      consumes:
      - application/json
      description: Hello World
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.MessageResponse'
      summary: Hello World
      tags:
      - Hello
swagger: "2.0"
