basePath: /
definitions:
  beepicker.ScheduleSaveRequest:
    properties:
      ECRN:
        items:
          type: integer
        type: array
      SCRN:
        items:
          type: integer
        type: array
      scheduleName:
        type: string
    type: object
  main.MessageResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Bu, BeeHub Ders Seçim Botu için API dokümantasyonudur.
  title: BeeHub Ders Seçim Botu API
  version: "1.0"
paths:
  /auth/login:
    get:
      consumes:
      - application/json
      produces:
      - text/html
      responses: {}
      summary: Hello World
      tags:
      - Login
  /beePicker/courses:
    get:
      produces:
      - application/json
      responses: {}
      summary: Retrieves courses from the BeePicker.
      tags:
      - BeePicker
  /beePicker/schedule:
    get:
      produces:
      - application/json
      responses: {}
      summary: Retrieves schedules from the BeePicker.
      tags:
      - BeePicker
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body containing the ECRN
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/beepicker.ScheduleSaveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Selection successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Selects a course from the BeePicker.
      tags:
      - BeePicker
  /hello:
    get:
      consumes:
      - application/json
      description: Hello World
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.MessageResponse'
      summary: Hello World
      tags:
      - Hello
swagger: "2.0"
