basePath: /
definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  beepicker.pickRequest:
    properties:
      courseCodes:
        items:
          type: string
        type: array
    type: object
  beepicker.scheduleSaveRequest:
    properties:
      ECRN:
        items:
          type: integer
        type: array
      SCRN:
        items:
          type: integer
        type: array
      scheduleName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Bu, BeeHub Ders Seçim Botu için API dokümantasyonudur.
  title: BeeHub Ders Seçim Botu API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: Hello World
      tags:
      - Login
  /auth/profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: Hello World
      tags:
      - Profile
  /beePicker/courses:
    get:
      produces:
      - application/json
      responses: {}
      summary: Retrieves courses from the BeePicker.
      tags:
      - BeePicker
  /beePicker/pick:
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body containing the course codes
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/beepicker.pickRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Picking successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Picks a course from the kepler.
      tags:
      - BeePicker
  /beePicker/schedule:
    get:
      produces:
      - application/json
      responses: {}
      summary: Retrieves schedules from the BeePicker.
      tags:
      - BeePicker
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body containing the ECRN
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/beepicker.scheduleSaveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Selection successful
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Selects a course from the BeePicker.
      tags:
      - BeePicker
swagger: "2.0"
